### ISSUE TITLE
Clarifying the argument `rtt`

### ISSUE THREAD

**Issue by DarylWM** [markmipt/ms1searchpy#3]
Hi Mark. Would you please clarify the role of the argument `rtt`? The help says it's the retention time threshold in sigma but I'm not sure what that means. If it's the standard deviation of the monoisotopic peak in RT, is it seconds or minutes?

Thanks,
Daryl.

**Comment by DarylWM** [comment]
Had another look at the code and I think it's the number of standard deviations.

**Comment by markmipt** [comment]
Actually, that parameter is deprecated. Thanks for reporting, it was fixed it in the new commit. 

Previously, it was used to remove some part of false peptide matches at the cost of some true matches. For example, using 2 (instead of 3) standard deviation threshold (for difference between predicted and experimental retention times) removed ~33% of false peptide matches (due to uniform distribution of false matches) and ~5% (normal distribution).
